export PATH=/tmp/code-review-runtime/node_modules/.bin:$PATH
export BROWSER=none HOST=127.0.0.1 PORT=3000
export REACT_APP_USE_EMULATORS=true REACT_APP_EMULATOR_HOST=127.0.0.1
export REACT_APP_AUTH_EMULATOR_PORT=9099 REACT_APP_FIRESTORE_EMULATOR_PORT=8080
export REACT_APP_FUNCTIONS_EMULATOR_PORT=5001 REACT_APP_STORAGE_EMULATOR_PORT=9199
export REACT_APP_PROJECT_ID=demo-review-pass5 REACT_APP_API_KEY=synthetic-review-key
export REACT_APP_AUTH_DOMAIN=demo-review-pass5.firebaseapp.com REACT_APP_STORAGE_BUCKET=demo-review-pass5.appspot.com
export REACT_APP_MESSAGING_SENDER_ID=000000000000 REACT_APP_APP_ID=1:000000000000:web:syntheticreview
export REACT_APP_MEASUREMENT_ID=review-disabled
