services:
  # Frontend React application only
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.dev
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_USE_EMULATOR=true
      - REACT_APP_EMULATOR_HOST=host.docker.internal  # Access host from container
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
      - REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
      - REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
      - REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}
      - REACT_APP_APP_ID=${REACT_APP_APP_ID}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allow container to reach host services

volumes:
  node_modules: