services:
  # Frontend React application
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend.dev
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_USE_EMULATORS=${REACT_APP_USE_EMULATORS}
      - REACT_APP_API_KEY=${REACT_APP_API_KEY}
      - REACT_APP_AUTH_DOMAIN=${REACT_APP_AUTH_DOMAIN}
      - REACT_APP_PROJECT_ID=${REACT_APP_PROJECT_ID}
      - REACT_APP_STORAGE_BUCKET=${REACT_APP_STORAGE_BUCKET}
      - REACT_APP_MESSAGING_SENDER_ID=${REACT_APP_MESSAGING_SENDER_ID}
      - REACT_APP_APP_ID=${REACT_APP_APP_ID}
      - REACT_APP_EMULATOR_HOST=localhost
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    depends_on:
      - emulators
    networks:
      - dnd-network

  # Firebase Emulators
  emulators:
    build:
      context: ..
      dockerfile: docker/Dockerfile.emulators
    volumes:
      - ./emulators/data:/app/data
      - ./emulators/logs:/app/logs
      - ../firebase/firestore.rules:/app/firestore.rules
      - ../firebase/firestore.indexes.json:/app/firestore.indexes.json
      - ../firebase/storage.rules:/app/storage.rules
      - ../firebase/functions:/app/functions # Functions directory mount
    ports:
      - "4000:4000" # Emulator UI
      - "4400:4400" # Hub
      - "4500:4500" # Reserved
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
      - "9150:9150" # Firestore UI websocket
      - "9199:9199" # Storage
      - "5001:5001" # Functions
    environment:
      - NODE_OPTIONS=--max_old_space_size=2048
    networks:
      - dnd-network
    stop_signal: SIGTERM
    stop_grace_period: 60s

volumes:
  node_modules:

networks:
  dnd-network:
    driver: bridge