# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build app in Docker container and extract build artifacts
      - name: Build app in container
        run: |
          # Copy production env
          cp .env.production .env
          
          # Build using Docker
          docker build -t app-builder -f docker/Dockerfile.frontend.prod .
          docker create --name temp-container app-builder
          docker cp temp-container:/usr/share/nginx/html ./build
          docker rm temp-container
      
      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DND_CAMPAIGN_COMPANION }}
          channelId: live
          projectId: dnd-campaign-companion